name: Ansible

on: 
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./ansible

jobs:

  ansible:
    name: Ansible Stack Stage
    runs-on: ubuntu-latest
    environment: stage
    
    env:
      stack: stage
      SSH_KEY: ${{ secrets.SSH_KEY }}
      IP_ADDRESS: ${{ secrets.IP_ADDRESS_GRAFANA }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install ansible python3-pip -y
            

      - name: SSH Test
        run: |
            mkdir ~/.ssh
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            #ssh-keyscan -t rsa $IP_ADDRESS

            ssh -i ~/.ssh/id_rsa ubuntu@$IP_ADDRESS "id"
      
      