name: Ansible

on: 
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./ansible

jobs:

  ansible:
    name: Ansible Stack Stage
    runs-on: ubuntu-latest
    environment: stage
    
    env:
      stack: stage

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install awscli git ansible python3-pip jq -y
            

      - name: SSH Test
        run: |
            touch grafanassh.pem
            echo -e "${{ secrets.SSH_KEY }}" >> grafanassh.pem
            chmod 400 grafanassh.pem
            echi "ssh -i grafanassh.pem ubuntu@${{ secrets.IP_ADDRESS_GRAFANA }} "id"""
      
      