name: Ansible

on: 
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./ansible

jobs:

  ansible:
    name: Ansible Stack Stage
    runs-on: ubuntu-latest
    environment: stage
    
    env:
      stack: stage
      SSH_KEY: ${{ secrets.SSH_KEY }}
      IP_ADDRESS: ${{ secrets.IP_ADDRESS_GRAFANA }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install ansible python3-pip -y
            

      - name: SSH 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock 
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan ${{ secrets.IP_ADDRESS_GRAFANA }} >> ~/.ssh/known_hosts
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/grafana
            chmod 600 ~/.ssh/grafana

            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add ~/.ssh/grafana 

            ssh -i ~/.ssh/grafana ubuntu@${{ secrets.IP_ADDRESS_GRAFANA }} "id"
      
      